name: Build Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC (BeiJing 00:00) on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    paths-ignore:
      - docs/**
      - '**/README.md'
  pull_request:
    paths-ignore:
      - docs/**
      - '**/README.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Check
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1.2.1
      - name: Build
        shell: bash
        run: zig build
      - name: Build for Linux
        if: ${{ success()}}
        shell: bash
        run: |
          zig build-exe ./zboot.zig -target x86_64-linux-gnu -O ReleaseSmall
          cp ./zboot ./zig-out/zboot-linux
      - name: Build for Windows
        if: ${{ success()}}
        shell: bash
        run: |
          zig build-exe ./zboot.zig -target x86_64-windows-gnu -O ReleaseSmall
          cp ./zboot.exe ./zig-out/zboot-windows.exe
      - name: Upload artifact
        if: ${{ success()}}
        uses: actions/upload-artifact@v4
        with:
          # Upload entire repository
          path: 'zig-out'